#!/bin/bash
#
# Yet Another UserAgent Analyzer
# Copyright (C) 2013-2019 Niels Basjes
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an AS IS BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# Client side pre-commit hook to assist the committers to ensure the commit messages
# follow the chosen convention.

. git-sh-setup  # for die

#LOGMESSAGE_FORMAT='^[A-Z][A-Z]*-[1-9][0-9]*: .*'
COMMIT_MSG_FILE=$1

echo "=========================="
echo "Doing basic commit validation"

echo -n "= Single line commit message: "
COMMIT_LINES=$(cat ${COMMIT_MSG_FILE} | wc -l)
if [ ${COMMIT_LINES} -eq 1 ];
then
  echo "Ok"
else
  echo "Fail: Found ${COMMIT_LINES} lines"
  exit 1
fi

#echo -n "= Commit message format: "
#if grep -q "${LOGMESSAGE_FORMAT}" ${COMMIT_MSG_FILE}
#then
#    echo "Ok"
#else
#    echo "Fail: Must be in this format: ${LOGMESSAGE_FORMAT}"
#    exit 1
#fi
#
#ISSUE_ID=$(head -1 ${COMMIT_MSG_FILE} | cut -d':' -f1)
#
#echo -n "= CHANGES.txt mentions ${ISSUE_ID}: "
#if grep -q "${ISSUE_ID}[^0-9]" CHANGES.txt
#then
#    echo "Ok"
#else
#    echo "Fail"
#    exit 1
#fi

# Fail if there is a DONOTCOMMIT in one of the files to be committed
git-diff-index -p -M --cached HEAD -- | grep '^+' | fgrep DONOTCOMMIT && die Blocking commit because string DONOTCOMMIT detected in patch

echo "=========================="

exit 0
