#!/bin/bash
#
# Yet Another UserAgent Analyzer
# Copyright (C) 2013-2022 Niels Basjes
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an AS IS BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# Client side pre-commit hook to assist the committers to ensure the commit messages
# follow the chosen convention.

SCRIPTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"

function die() {
  #https://wiki.archlinux.org/index.php/Color_Bash_Prompt
  # Reset
  export Color_Off='\e[0m'      # Text Reset

  # High Intensity
  export IRed='\e[0;91m'        # Red
  export IYellow='\e[0;93m'     # Yellow
  export IBlue='\e[0;94m'       # Blue
  export IWhite='\e[0;97m'      # White

  # Bold High Intensity
  export BIRed='\e[1;91m'       # Red
  export BIBlue='\e[1;94m'      # Blue

  echo -e "${Color_Off}"
  echo -e "${IWhite}[${BIRed}FATAL${IWhite}] ${IYellow}/========================================================================"
  echo -e "${IWhite}[${BIRed}FATAL${IWhite}] ${IYellow}| ${BIRed} ---------->>> THE CHANGES WERE NOT COMMITTED ! <<<---------- ${IYellow}"
  echo -e "${IWhite}[${BIRed}FATAL${IWhite}] ${IYellow}| ${BIRed} $@ ${IYellow}"
  echo -e "${IWhite}[${BIRed}FATAL${IWhite}] ${IYellow}\\========================================================================"
  echo -e "${Color_Off}"
  exit 1
}

for check in "${SCRIPTDIR}"/commit-msg.d/*sh; do
   . ${check}
done

echo "=========================="

exit 0
